// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnvpfjoaqjabcyjdnixk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudnBmam9hcWphYmN5amRuaXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTI2MDIsImV4cCI6MjA2NTE2ODYwMn0.ypRIhpGNBH7EoDubtpJ-U4AmEyIdXPsZJRXjnoHceNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);